### PR TITLE
docs: add troubleshooting section for Run locally

### PR DESCRIPTION
**Pull request by yshyn-iohk**

### CODE REVIEW

**Review by FabioPinheiro — COMMENTED** [review]
In that case you need to remove the other place with Troubleshooting

**Comment by yshyn-iohk** [comment]
@FabioPinheiro, where is another section with Troubleshooting? I cannot find it in README.md

**Comment by FabioPinheiro** [comment]
yes its missing. We pointed to it but was removed.

**Review by FabioPinheiro — APPROVED** [review]

**Review by petevielhaber — COMMENTED** [review]
Reviewed

**Pull request merged**
