### PR TITLE
Return 202 HTTP code (for DID Comm)

### PR DESCRIPTION
**Pull request by FabioPinheiro**
The recommendation from the didcomm-messaging specs is to return a 202 Accepted. See https://identity.foundation/didcomm-messaging/spec/#https

Resolves issue #160

### CODE REVIEW

**Comment by FabioPinheiro** [comment]
I tested it by hand with curl is returning a 202 now`< HTTP/1.1 202 Accepted`

**Comment by FabioPinheiro** [comment]
@antonbaliasnikov we need to fix the tests =P
https://github.com/input-output-hk/atala-prism-mediator/pull/162/checks?check_run_id=18333751277

**Review by mineme0110 — APPROVED** [review]

**Comment by mineme0110** [comment]
LGTM
Only Integration test need to updated

**Comment by FabioPinheiro** [comment]
Test suite fixed on https://github.com/input-output-hk/didcomm-v2-mediator-test-suite/pull/8

**Comment by FabioPinheiro** [comment]
It's passed all the tests except the changes made up by another PR https://github.com/input-output-hk/atala-prism-mediator/pull/157.
So we can merge
```
STEP FAILURE: java.lang.AssertionError: 
Expecting a value that is equal to: <"e.p.me.res.storage">
But got...........................: <"e.p.crypto.message.dejavu">
```

**Pull request merged**
